<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediaModule.Application\MediaModule.Application.csproj" />
    <ProjectReference Include="..\MediaModule.Domain\MediaModule.Domain.csproj" />
    <ProjectReference Include="..\MediaModule.Infrastructure\MediaModule.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\logo.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\app.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
